"""empty message

Revision ID: 311ed1f98d6
Revises: 404f120e9ed
Create Date: 2018-04-03 10:34:22.137981

"""

# revision identifiers, used by Alembic.
revision = '311ed1f98d6'
down_revision = '404f120e9ed'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('path', sa.String(length=50), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_deploy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('script', sa.String(length=50), nullable=True),
    sa.Column('args', sa.String(length=50), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('command', sa.String(length=50), nullable=True),
    sa.Column('autostart', sa.Boolean(), nullable=True),
    sa.Column('autorestart', sa.Boolean(), nullable=True),
    sa.Column('startsecs', sa.String(length=50), nullable=True),
    sa.Column('startretries', sa.Integer(), nullable=True),
    sa.Column('user', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('redirect_stderr', sa.Boolean(), nullable=True),
    sa.Column('stdout_logfile_maxbytes', sa.String(length=50), nullable=True),
    sa.Column('stdout_logfile_backups', sa.String(length=50), nullable=True),
    sa.Column('stdout_logfile', sa.String(length=50), nullable=True),
    sa.Column('stopasgroup', sa.Boolean(), nullable=True),
    sa.Column('killasgroup', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_run')
    op.drop_table('project_deploy')
    op.drop_table('project_config')
    op.drop_table('project')
    ### end Alembic commands ###
