"""empty message

Revision ID: 381d56f306
Revises: 311ed1f98d6
Create Date: 2018-04-08 14:39:58.046268

"""

# revision identifiers, used by Alembic.
revision = '381d56f306'
down_revision = '311ed1f98d6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('path', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'path')
    ### end Alembic commands ###
