"""first

Revision ID: 3cb40a7a2f8
Revises: None
Create Date: 2018-03-28 14:21:48.968040

"""

# revision identifiers, used by Alembic.
revision = '3cb40a7a2f8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
