"""empty message

Revision ID: 404f120e9ed
Revises: 58e00d7545b
Create Date: 2018-04-02 14:39:28.533162

"""

# revision identifiers, used by Alembic.
revision = '404f120e9ed'
down_revision = '58e00d7545b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('tag', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=80), nullable=True),
    sa.Column('content', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge')
    ### end Alembic commands ###
