"""empty message

Revision ID: 5769e360259
Revises: 381d56f306
Create Date: 2018-04-08 15:05:18.480215

"""

# revision identifiers, used by Alembic.
revision = '5769e360259'
down_revision = '381d56f306'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
