"""empty message

Revision ID: 58e00d7545b
Revises: 36b542c5b38
Create Date: 2018-03-30 09:27:21.104068

"""

# revision identifiers, used by Alembic.
revision = '58e00d7545b'
down_revision = '36b542c5b38'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=80), nullable=True),
    sa.Column('hostname', sa.String(length=80), nullable=True),
    sa.Column('port', sa.String(length=80), nullable=True),
    sa.Column('is_active', sa.String(length=80), nullable=True),
    sa.Column('public_ip', sa.String(length=80), nullable=True),
    sa.Column('number', sa.String(length=80), nullable=True),
    sa.Column('vendor', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('sn', sa.String(length=80), nullable=True),
    sa.Column('cpu_model', sa.String(length=80), nullable=True),
    sa.Column('cpu_count', sa.String(length=80), nullable=True),
    sa.Column('cpu_cores', sa.String(length=80), nullable=True),
    sa.Column('memory', sa.String(length=80), nullable=True),
    sa.Column('disk_total', sa.String(length=80), nullable=True),
    sa.Column('disk_info', sa.String(length=80), nullable=True),
    sa.Column('platform', sa.String(length=80), nullable=True),
    sa.Column('os', sa.String(length=80), nullable=True),
    sa.Column('os_version', sa.String(length=80), nullable=True),
    sa.Column('os_arch', sa.String(length=80), nullable=True),
    sa.Column('hostname_raw', sa.String(length=80), nullable=True),
    sa.Column('labels', sa.String(length=80), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('date_created', sa.String(length=80), nullable=True),
    sa.Column('comment', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset')
    ### end Alembic commands ###
