- hosts: "{{ansible_hosts}}"
  gather_facts: no

  tasks:
  - name: echo choice
    shell: bash -c "echo {{choice}} ;sleep 20"
    register: echo_choice
  - debug: var=echo_choice
    
  - name: echo input
    shell: bash -c "echo {{input}} ;sleep 20"
    register: echo_input
  - debug: var=echo_input
    

