"""‘v1.1’

Revision ID: 4d459d29c714
Revises: 
Create Date: 2019-03-27 22:19:23.480618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d459d29c714'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=80), nullable=True),
    sa.Column('hostname', sa.String(length=80), nullable=True),
    sa.Column('port', sa.String(length=80), nullable=True),
    sa.Column('is_active', sa.String(length=80), nullable=True),
    sa.Column('public_ip', sa.String(length=80), nullable=True),
    sa.Column('number', sa.String(length=80), nullable=True),
    sa.Column('vendor', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('sn', sa.String(length=80), nullable=True),
    sa.Column('cpu_model', sa.String(length=80), nullable=True),
    sa.Column('cpu_count', sa.String(length=80), nullable=True),
    sa.Column('cpu_cores', sa.String(length=80), nullable=True),
    sa.Column('memory', sa.String(length=80), nullable=True),
    sa.Column('disk_total', sa.String(length=80), nullable=True),
    sa.Column('disk_info', sa.String(length=80), nullable=True),
    sa.Column('platform', sa.String(length=80), nullable=True),
    sa.Column('os', sa.String(length=80), nullable=True),
    sa.Column('os_version', sa.String(length=80), nullable=True),
    sa.Column('os_arch', sa.String(length=80), nullable=True),
    sa.Column('hostname_raw', sa.String(length=80), nullable=True),
    sa.Column('labels', sa.String(length=80), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('date_created', sa.String(length=80), nullable=True),
    sa.Column('comment', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('tag', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=80), nullable=True),
    sa.Column('content', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('path', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password_hash', sa.String(length=164), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('project_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('path', sa.String(length=50), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_deploy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('script', sa.String(length=50), nullable=True),
    sa.Column('args', sa.String(length=50), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('command', sa.String(length=50), nullable=True),
    sa.Column('autostart', sa.Boolean(), nullable=True),
    sa.Column('autorestart', sa.Boolean(), nullable=True),
    sa.Column('startsecs', sa.String(length=50), nullable=True),
    sa.Column('startretries', sa.Integer(), nullable=True),
    sa.Column('user', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('redirect_stderr', sa.Boolean(), nullable=True),
    sa.Column('stdout_logfile_maxbytes', sa.String(length=50), nullable=True),
    sa.Column('stdout_logfile_backups', sa.String(length=50), nullable=True),
    sa.Column('stdout_logfile', sa.String(length=50), nullable=True),
    sa.Column('stopasgroup', sa.Boolean(), nullable=True),
    sa.Column('killasgroup', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_run')
    op.drop_table('project_deploy')
    op.drop_table('project_config')
    op.drop_table('user')
    op.drop_table('project')
    op.drop_table('knowledge')
    op.drop_table('asset')
    # ### end Alembic commands ###
