# Generated by Django 2.2 on 2018-09-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='addr',
            field=models.CharField(default='west zhongshan road', max_length=128),
        ),
    ]
