# Generated by Django 2.2 on 2018-09-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20180911_0301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Db',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('db_name', models.CharField(max_length=10, unique=True)),
                ('host', models.CharField(max_length=20)),
                ('port', models.CharField(max_length=10)),
                ('database', models.CharField(max_length=10)),
                ('user', models.CharField(max_length=10)),
                ('passwd', models.CharField(max_length=10)),
            ],
        ),
    ]
