# Generated by Django 2.2 on 2018-09-11 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_db'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Db',
            new_name='db_config',
        ),
    ]
